noir-lang/acvm

acir/src/circuit/blackbox_functions.rs

I noticed that we don't support looking up the AES blackbox function so I've added an entry for it and a test to check that we maintain the invariant `BlackBoxFunc::lookup(bb_func.name()) == Some(bb_func)` to help avoid this happening again.
We can automatically track this for new variants by adding the [strum](https://crates.io/crates/strum) crate as a dev-dependency but if we don't want to add this then we can just maintain a static array of all the enum variants.

Add lookup entry for AES blackbox function

---

acir/Cargo.toml
acir/src/circuit/blackbox_functions.rs

We now automatically check that all variants of `BlackBoxFunc` satisfy the `consistent_function_names` test
closes #31

Generalise `consistent_function_names` to automatically handle new variants

---

acvm/Cargo.toml
acvm/src/lib.rs
acvm/src/pwg/arithmetic.rs
acvm/src/pwg/logic.rs

This implements the changes described in https://github.com/noir-lang/noir/pull/520#discussion_r1052624508.
This is sensible imo as 
- `OpcodeResolution` doesn't make sense for a circuit-level function such as `PartialWitnessGenerator.solve` (what does "Skip" mean when solving a circuit?)
- We can define error messages here in ACVM for the failure modes of solving the circuit. Callers then don't need to understand the reasoning behind all the `OpcodeResolution` variants to be able to separate success vs failure. 
I've lumped in a change to simplify `BlackBoxFuncCall` in the last commit which improves readability imo, happy to revert this if this is unwanted.

Split off errors from `OpcodeResolution`

---

acir/src/circuit/directives.rs
acir/src/circuit/opcodes.rs
acvm/src/lib.rs
acvm/src/pwg/directives.rs

Resolves log statement issue in noir-lang repo: https://github.com/noir-lang/noir/issues/383
This includes a Log directive and the logic in the PWG for solving it.
I added a Log directive that takes a LogInfo enum. This enum can either be finalized string output or a vector of witnesses whose data has to be fetched when solving the circuit. I then added the logic for printing single values and arrays in the PWG. This logic follows similar logic from acir gen when we can construct a finalized output string.

feat: Add Log Directive

---

acvm/src/compiler/fallback.rs
acvm/src/pwg/logic.rs

Remaining instances of `gc` (gadget call) have been renamed to `bb_func_call`.
N/A
N/A

chore(acvm): rename remaining references to gadget calls

---

acir/Cargo.toml
acir/src/lib.rs
acvm/Cargo.toml
stdlib/Cargo.toml
stdlib/src/fallback.rs

Resolves https://github.com/noir-lang/acvm/issues/51
expose acir_field through acir
1. add `acir` to have two features that references features in `acir_field`
2. change `acvm` features to reference feaures of `acir`
3. delete `acir_field` dependencies in `acvm` and `stdlib`

chore: expose acir_field through acir

---

acvm/src/lib.rs

Resolves #64 #65 #46 
Add ACVM methods for preprocessing and proof creation from proving and verification keys 
This PR simply adds methods to the `ProofSystemCompiler` trait for both preprocessing (proving and verification key generation) as well as new methods to create proofs with a proving key and to verify those proofs with a verification key. 
These methods are tested by fully integrating with a given backend. Currently this is only being tested with the `aztec_backend`. After the `aztec_backend` is fully working I will also change the `marlin_arkworks_backend` to reflect the new acvm. We should wait on merging this PR until the backends are fully working with the respective changes.  

feat: Preprocess methods for ACVM interface 

---

acvm/src/lib.rs

chore: fix clippy

---

.github/workflows/rust.yml

This updates ACVM's CI to use our reusable workflows. This will keep CI in sync across all our repositories.

chore(ci): Leverage reusable workflows

---

acir_field/src/generic_ark.rs

Better print for field elements

chore(field): improve field formatting

---

acir_field/src/generic_ark.rs

This PR adds test for methods in acir_field, so that we can test if a new version of arkworks breaks them.

chore: add tests for `from_hex` and `to_hex`

---

acir_field/Cargo.toml
acir_field/src/generic_ark.rs

Resolves #68 
Update Arkworks' dependencies on `acir_field`'s `Cargo.toml`.
- Update `ark-bn254` from `0.3.0` to `0.4.0`.
- Update `ark-bls12-381` from `0.3.0` to `0.4.0`.
- Update `ark-ff` from `0.3.0` to `0.4.0`.
- Add `ark-serialize 0.4.0`.
- Remove `ark-bn254` from dev-dependencies.
-
The additional context was provided in #68

feat: Update Arkworks' dependencies on `acir_field`

---

acir/src/circuit/black_box_functions.rs

Resolves #90 
Keccak256 looks exactly the same as Blake256 and Sha256 from an opcode perspective, so it was mostly just giving it an opcode number and copying the function definition from sha256

feat(acir)!: Add Keccak256 Opcode

---

acvm/src/pwg/directives.rs

Resolves #94 
We just now trim the zeroes for hex output. 
I have seen the result of this output when testing the println PR on the Noir repo. 

fix: Clean up Log Directive hex output 

---

acir/src/circuit/mod.rs

Related to https://github.com/noir-lang/noir/pull/851#discussion_r1108927283
This PR swaps out the implementation of `PublicInputs` to use a `BTreeSet` for native deduplication of public inputs mapped to the same witness index.
This should only create a breaking change up in `noirc_evaluator` where we're planning on switching this out for a `BTreeSet` anyway so this will avoid us having to convert to a `Vec` before creating the `Circuit` up there.
We can 

feat(acir)!: automatically dedupe `PublicInputs` using a `BTreeSet`

---

.github/workflows/publish.yml
.github/workflows/release.yml

Resolves #93
This adds automatic publishing to crates.io when a release-please PR is merged (after the tags are created). I separated this out into a separate workflow and dispatch to it so we can manually run the publish workflow if we need, which can be useful for recovering from a failed build, debugging, etc.
Since cargo doesn't support publishing everything in a workspace, we have to publish the exact correct order and this will need to be updated if the dependencies change.

feat(ci): Publish crates upon release

---

release-please-config.json

When I added release-please to the project, I missed the fact that the dependency versions were specified in the Cargo.toml workspace file. This adds updaters to ensure that the dependency versions are updated by release-please too.
I'm not sure I totally agree with specifying the local dependencies in the workspace like this but I didn't want to make that larger change just for the fix.

fix(ci): Update dependency versions in the workspace file

---

.rustfmt.toml
acir/src/circuit/black_box_functions.rs
acir/src/circuit/directives.rs
acir/src/circuit/mod.rs
acir/src/circuit/opcodes.rs
acir/src/native_types/arithmetic.rs
acir/src/native_types/linear.rs
acir_field/src/generic_ark.rs
acvm/src/compiler/optimizers/general.rs
acvm/src/compiler/transformers/csat.rs
acvm/src/lib.rs
acvm/src/pwg/directives.rs
acvm/src/pwg/hash.rs
acvm/src/pwg/logic.rs
acvm/src/pwg/range.rs

This repository previously did not have a `.rustfmt.toml` file. I've copied over the file from the main noir repo and formatting is now noticeably more compact.

Copy .rustfmt.toml from noir repo

---

cspell.json

We're getting a lot of spelling warnings appear (e.g. https://github.com/noir-lang/acvm/pull/107/files) so I've added this to the dictionary.

chore: add keccak to CSpell dictionary

---

acvm/src/lib.rs

Resolves #101 
The `ProofSystemCompiler` trait now takes `&Circuit` rather than `Circuit`.

feat!: update `ProofSystemCompiler` methods to take `&Circuit`

---

acvm/src/lib.rs

Resolves #110 
I've changed the argument types from `Vec<u8>` to `&[u8]`.

feat!: update `ProofSystemCompiler` to not take ownership of keys

---

acvm/src/lib.rs

chore: deprecate `eth_contract_from_cs`
Resolves #102 
`eth_contract_from_cs` is now deprecated and `eth_contract_from_vk` has been added which takes a `&[u8]` rather than a `Circuit`.

feat(acvm): add `eth_contract_from_vk` to `SmartContract

---

acvm/src/lib.rs

Resolves PR review comment https://github.com/noir-lang/acvm/pull/105#pullrequestreview-1309740077
This PR pulls out the minimal changes (switching from a recursive to non-recursive solve method) from #114 to unblock #105.

chore(acvm): switch to non-recursive solve method

---

acvm/src/lib.rs

~~`verify_from_cs` and~~ `verify_with_vk` now accept a `BTreeMap<Witness, FieldElement>`. This is used in combination with the explicit ABI->Witness map in https://github.com/noir-lang/noir/pull/851 to handle multiple ABI fields (params + return value) being mapped to the same witness index semantically.
I've reverted the change to `verify_from_cs` as we should leave it unchanged until we remove it.

feat(acvm)!: switch to accepting public inputs as a map

---

.github/workflows/publish.yml

Resolves issue with publishing where `acvm` can't find the correct version of `acvm_stdlib`
https://github.com/noir-lang/acvm/actions/runs/4262171236/jobs/7417352533
I've swapped acvm and acvm_stdlib so that the acvm_stdlib crate is published first.
- [] I have tested the changes locally.

fix(ci): publish acvm_stdlib before acvm

---

acir/src/lib.rs
acir_field/Cargo.toml
acir_field/src/lib.rs
acvm/Cargo.toml
acvm/src/lib.rs
stdlib/src/lib.rs

Cargo now throws warnings if we've defined a dependency but don't make use of it.
Removed `blake2`, `num_traits` and `ark-serialize` from `acir_field`.

chore: remove unused crate dependencies

---

acir/src/circuit/mod.rs

This test is testing deprecated code so having a warning appear here doesn't make sense.

chore(acir): silence deprecation warning in test

---

acvm/src/lib.rs
acvm/src/pwg.rs
acvm/src/pwg/arithmetic.rs
acvm/src/pwg/directives.rs

We now derive `OpcodeResolutionError::from<OpcodeNotSolvable>()` which avoids some wrapping of errors.

chore(acvm): implement `From` for OpcodeNotSolvable

---

acir/src/native_types/arithmetic.rs

Resolves TODOs on https://github.com/noir-lang/noir/blob/ed0e1ab4c7a3461da1a3fd500335d146ce43176c/crates/noirc_evaluator/src/ssa/acir_gen.rs#L120-L211
I've copied across a number of functions from `noirc_evaluator` to make them methods on `Expression`.
As part of this I noticed that we're not properly displaying expressions of the form `f(x) = mx, m != 1` so I've fixed that at the same time.

feat(acir): add useful methods from `noirc_evaluator` onto `Expression`

---

acir/src/native_types/arithmetic.rs

We currently only implement `Expression::from<&Witness>` and `Expression::from<&FieldElement>`, I've implemented `Expression::from<Witness>` and `Expression::from<FieldElement>` as otherwise we need to borrow these values before we can convert them.

feat(acir): implement `Expression::from()` for both values and references

---

acir/src/native_types/arithmetic.rs
acir/src/native_types/witness.rs

I've removed the functionally dead code of `UnknownWitness` as [we don't use it anywhere](https://github.com/search?q=org%3Anoir-lang%20UnknownWitness&type=code).
It is in the public interface however so this is a breaking change.
N/A
N/A

chore(acir)!: remove `UnknownWitness`

---

acir/src/native_types/arithmetic.rs
stdlib/src/fallback.rs

chore(acir)!: rename `term_addition` to `push_addition_term`
Resolves one item from https://github.com/noir-lang/acvm/issues/53
> term_multiplication() and term_addition() are not clear and should be renamed into push_multiplication_term() and push_linear_term()
These two methods have been renamed to be clearer about what they do.
This is a relatively minor change but is breaking. We should delay merging until we are going to have a breaking release.

chore(acir)!: rename `term_multiplication` to `push_multiplication_term`

---

acir/src/circuit/directives.rs
acir/src/circuit/opcodes.rs
acvm/src/lib.rs
acvm/src/pwg/directives.rs
stdlib/src/fallback.rs

In order to keep ACIR simple, I remove the endianness handling so that it only support to_radix_le. The gate as been renamed accordingly.

chore!(acir): remove is_little_endian from to_radix

---

acvm/src/lib.rs

Resolves #139 
I've removed the deprecated methods from `ProofSystemCompiler` so that they no longer need to be implemented by backends.

chore(acvm)!: remove `prove_with_meta` and `verify_from_cs` from `ProofSystemCompiler`

---

acvm/Cargo.toml
acvm/src/lib.rs

Related to https://github.com/noir-lang/noir/issues/870
Move to a faster checksum https://github.com/srijs/rust-crc32fast
add `crc32fast = "1.3.2"` to acvm

chore: add a checksum method for the constraint system

---

acir/src/circuit/opcodes.rs
acvm/src/compiler.rs
acvm/src/compiler/transformers/fallback.rs
acvm/src/compiler/transformers/mod.rs
acvm/src/lib.rs
acvm/src/pwg/block.rs

Add ROM and RAM opcodes in order to support dynamic arrays for Aztec Backend.
The BLOCK opcode handles conditional writes by using an expression for the memory operation, but Barretenberg does not support this. We add RAM and ROM opcodes to help the backend to specify what it does support, so that noir can decide which opcode to use based on the array usage and the supported opcodes:
ROM: an initialisation phase with writes on constant indexes, then only read access
RAM: an initialisation phase with writes on constant indexes, then dynamic read or write access
BLOCK: the most flexible, if the backend supports it, it must enforce the correct constraints.
If the backend supports BLOCK, noir will use this opcode because it is more efficient,
if the backend supports RAM/ROM, then noir will …

feat!(acir): Add RAM and ROM opcodes

---

acvm/src/lib.rs

inputs
Resolves #153
Stall instead of fail when encountering black box function inputs.

fix(pwg): stall instead of fail for unassigned black box

---

acir/src/circuit/directives.rs

Bug fix where the Log directive was not being read even though it was being written. The log directive is now included in the `serialization_roundtrip` test as well. The PermutationSort directive was also missing from `serialization_roundtrip`. I added this as well for completeness and is all passing.

fix(acir)!: Read Log Directive

---

brillig_bytecode/src/lib.rs
brillig_bytecode/src/opcodes.rs

fix(brillig): Stop on VM failure 

---

acvm/src/lib.rs
acvm/src/pwg/brillig.rs
brillig_bytecode/src/lib.rs

…n at where the oracle was waiting

feat: Reduce brillig bytecodes sent to VM after oracle wait 

---

acvm/src/lib.rs
acvm/src/pwg/directives.rs

Resolves #179 
I've spun out `PartialWitnessGenerator::any_missing_assignment` and `PartialWitnessGenerator::solve_directives` into standalone functions and added a `&self` parameter to  `PartialWitnessGenerator::solve_black_box_function_call`.
I've also added a test to ensure that the `Backend` trait remains object safe (I couldn't find any lint, etc. which would enforce this so I've just attempted to pass a trait object to a function as this will fail to compile should `Backend` not be object safe.

feat(acvm)!: make `Backend` trait object safe

---

acvm/src/lib.rs

Resolves #184
This removes the deprecated `eth_contract_from_cs` function from the SmartContract trait. With https://github.com/noir-lang/aztec_backend/pull/84, we've made the switch to using `eth_contract_from_vk` to generate the solidity contract so we don't need to keep these around.
Removed the deprecated function.

chore(acvm)!: Remove `eth_contract_from_cs` from SmartContract trait

---

acir/src/circuit/mod.rs

This PR removes the deprecated `Circuit::to_bytes` and `Circuit::from_bytes` methods which were deprecated in [0.2.1](https://github.com/noir-lang/acvm/commit/054ffdd8664f59bc35575b23e44d03f8db87b1e9)

chore(acir)!: remove deprecated circuit serialization methods

---

acvm/src/lib.rs
brillig_bytecode/src/lib.rs
brillig_bytecode/src/opcodes.rs

This handles array outputs being returned from an oracle function. For complex types such as structs or nested structs the VM assumed these have been flattened when setting the Brillig bytecode.

feat: Brillig oracle array outputs

---

acvm/src/lib.rs

The ACVM pauses due to needing oracle outputs. When this was a singular opcode it was fine to simply return this oracle and then the ACVM caller can easily construct the new list of opcodes to be resolved. With Brillig we need the inputs and outputs of the brillig VM itself in order to process the opcode correctly. This PR adds the Brillig opcode as an unresolved opcode when we hit a Brillig oracle pause. This lets the ACVM caller to alter the brillig opcode without knowing or interacting with the encapsulating Brillig opcode's inputs and outputs. 

feat!: Return entire unresolved Brillig opcode during oracle pause

---

acvm/src/lib.rs
acvm/src/pwg/brillig.rs
brillig_bytecode/src/lib.rs
brillig_bytecode/src/opcodes.rs

feat!: Brillig oracle array inputs

---

acvm/src/lib.rs
acvm/src/pwg/brillig.rs
brillig_bytecode/src/lib.rs
brillig_bytecode/src/memory.rs
brillig_bytecode/src/opcodes.rs
brillig_bytecode/src/value.rs

No issue, fixes an issue from the #199 PR which was merged before my review
Changes OracleInput from a struct to an enumeration.
Also adds a helper method on VMOutputState to map the input values since I found the code was repeated three times.

fix: Change OracleInput to an enum

---

acvm/src/lib.rs
brillig_bytecode/src/lib.rs
brillig_bytecode/src/opcodes.rs

This PR switches oracle output from a single register index to an enum. With only one register index we assume that if an oracle returns multiple complex types these are all flattened into one array and we are currently handling oracle outputs always as an array. This also means we break arrays of size 1 as there is currently an assumption that if there is only one output value supplied to the oracle it must be a single register. We now require someone to differentiate between register and array oracle outptus and have a `Vec<OracleOutput>` as part of OracleData.
(Describe the changes in this PR. Point out …

feat!: Use OracleOutput enum in OracleData

---

acir_field/src/generic_ark.rs

We've got a huge number of instances of this code around multiple codebases so I think it's worth adding a quick way to create a field element to represent a boolean value.

feat: implement `FieldElement::from<bool>()`

---

acir/src/native_types/expression/mod.rs
acir/src/native_types/expression/operators.rs
acir/src/native_types/expression/ordering.rs
acir/src/native_types/mod.rs
acvm/src/compiler/transformers/fallback.rs
acvm/src/pwg/block.rs
stdlib/src/fallback.rs

The disorganised approach we have to implementing various traits on `Expression` has been bugging me. We've got a jumble of `From`s, maths operators and sorting operators all in the same file. This means that we're missing a few operator definitions which we'd want but it's not obvious that they're missing because there's not a defined order for them.
This PR takes `arithmetic.rs` and renames it to `expression.rs`, we then break this into three files:
- `mod.rs` which contains the bulk of the definition of `Expression` along with the main `impl`.
- `operators.rs` which defines `Add, Mul, Neg, Sub` on …

chore!: organise operator implementations for `Expression`

---

brillig_bytecode/src/lib.rs
brillig_bytecode/src/opcodes.rs

fix!: Oracle output array start as RegisterMemindex

---

brillig_bytecode/Cargo.toml
brillig_bytecode/src/lib.rs
brillig_bytecode/src/opcodes.rs

feat!: Handle result type of Binary Ops in Brillig

---

acvm/src/lib.rs

In our new merged `acvm-backend-barretenberg` crate, we're implementing the `Backend` trait directly on the `Barretenberg` struct rather than having a separate `Plonk` unit struct which then constructs `Barretenberg` when needed.
https://github.com/noir-lang/aztec_backend/blob/9fed6e52778d993d7742c46bbeec66087958c075/acvm_backend_barretenberg/src/lib.rs#L21-L26
This means that when we're actually using the backend in Nargo we need to construct the struct, i.e we need to call `let backend = Barretenberg::default()` rather than just being able to do `let backend = Plonk`.
Example: …

feat!: require `Backend` to implement `Default` trait

---

acvm/src/pwg/brillig.rs
brillig_bytecode/src/lib.rs
brillig_bytecode/src/opcodes.rs

feat(brillig)!: bitwise operators, shifts, and cleanup for BinaryOp::evaluate

---

acvm/src/pwg/brillig.rs

When setting brillig inputs the array id was being inserted even if the array values being inserted onto the heap were not fully solved yet by the acvm. This is now changed to check every element of the array to be inserted as initial memory to a brillig function. If an element is missing we stall the brillig and wait for the acvm to solve the witness in question.   

fix(brillig): Stall if a Brillig input array is not fully solved

---

acir/src/circuit/black_box_functions.rs

Resolves #25 
This PR updates the name of the `MerkleMembership` opcode to `ComputeMerkleRoot`. This signals that this opcode will begin to return the merkle root rather than a boolean flag for whether the passed value for the root matches the calculated value.
`aztec_backend` is ready to switch over to use `ComputeMerkleRoot` https://github.com/noir-lang/aztec_backend/pull/143 so we can make this change and begin propagating it up to noir.

feat(acir)!: replace `MerkleMembership` opcode with `ComputeMerkleRoot`

---

acvm/src/pwg/hash.rs

Resolves https://github.com/noir-lang/aztec_backend/pull/138#issuecomment-1522307087
I've pulled down the implementation of `BlackBoxFunc::HashToField128Security` from `aztec_backend`.
The hash implementations in ACVM now use the checked versions of the reading/writing witness values and return a proper `Result<OpcodeResolution, OpcodeResolutionError>` response to be passed back into ACVM.

feat(acvm)!: implement `hash_to_field_128_security`

---

Cargo.toml
acir_field/Cargo.toml
acvm/Cargo.toml
stdlib/Cargo.toml

Currently we're always turning on the `bn254` field due to default feature flags, this makes it impossible to use any different fields. I've fixed the feature flag setup so that only the field supplied to the `acvm` package gets turned on.
The second commit contains some miscellaneous cleanup of the various toml files.

fix: prevent `bn254` feature flag always being enabled

---

acvm/src/pwg/logic.rs
acvm/src/pwg/signature/ecdsa.rs

For consistency, all bb function implementations inside ACVM pass back a `Result<OpcodeResolution, OpcodeResolutionError>` so backends don't need to do anything other than forward the return value back into the ACVM.

feat(acvm)!: have all black box functions return `Result<OpcodeResolution, OpcodeResolutionError>`

---

acvm/src/pwg/range.rs

This was missed from https://github.com/noir-lang/acvm/pull/237

feat(acvm)!: return `Result<OpcodeResolution, OpcodeResolutionError>` from `solve_range_opcode`

---

Cargo.toml
acir/Cargo.toml

Resolves [(CI failure)](https://github.com/noir-lang/acvm/actions/runs/4830288705/jobs/8606331047)
We currently can't publish releases as `cargo publish` builds each package before publication and `acir` doesn't build without a feature flag being set (this wasn't encountered in real usage as we always set this flag when building in the context of the workspace/noir).
See: https://github.com/noir-lang/acvm/actions/runs/4830288705/jobs/8606331047
This PR sets a default feature flag so that `cargo publish` can build the `acir` crate in isolation.

fix(acir): add `bn254` as default feature flag

---

Cargo.toml
stdlib/Cargo.toml

Followup to https://github.com/noir-lang/acvm/pull/240

fix(acvm_stdlib): add default flag for fields in `acvm_stdlib`

---

Cargo.toml
acir_field/Cargo.toml
acvm/Cargo.toml

These dependencies are only used in a single crate so I've moved them down to be defined there.

chore: move `hex` and `blake2` deps down into crates

---

acvm/src/lib.rs

Resolves #235
This adds a required `Fallible` trait to ACVM backends. It is just used to create an Associated Type called Error that implements `std::error::Error` because traits aren't allowed to use `impl std::error::Error` and we don't want to require Backend implementors to have to Box all of their errors.
This uses the Error type to make other trait functions return Result types, which will allow Nargo to handle errors returned by a backend instead of the backend needing to panic. For example, the barretenberg wasm backend and https://github.com/TomAFrench/acvm-backend-groth16 both needed to unwrap/expect a lot of things but those errors should be bubbled up to nargo.
Planning to implement this throughout aztec_backend and nargo.

feat(acvm)!: Introduce Error type for fallible Backend traits

---

acvm/Cargo.toml
acvm/src/pwg/hash.rs

Less controversial version of #247 which just adds the Keccak hash function.

feat: Add Keccak Hash function

---

acvm/src/pwg/block.rs
acvm/src/pwg/directives.rs
acvm/src/pwg/logic.rs
acvm/src/pwg/oracle.rs

We currently have the functions [`insert_value`](https://github.com/noir-lang/acvm/blob/45c45f7cdb79c3ccb0373ca0e698b282d4dabc39/acvm/src/pwg.rs#L59-L76) and [`insert_witness`](https://github.com/noir-lang/acvm/blob/45c45f7cdb79c3ccb0373ca0e698b282d4dabc39/acvm/src/pwg/directives.rs#L175-L191). These are both almost identical, the only different being that `insert_value` with update the witness map before returning an `UnsatisfiedConstrain` error whereas `insert_witness` doesn't.
This difference is near meaningless (and if we decided that we wanted one behaviour in particular then we should be consistent with …

chore(acvm): Remove usage of `insert_witness` with `insert_value`

---

acir/src/circuit/opcodes.rs
acir/src/circuit/opcodes/black_box_function_call.rs
acir/src/circuit/opcodes/block.rs
acir/src/circuit/opcodes/oracle_data.rs

`acir/src/circuit/opcodes.rs` is pretty unwieldy to where it seems like people have dumped code in there without much thought for organisation. This PR splits up the definitions of individual opcode variants into separate modules.

chore(acir): Organise opcode definitions into separate modules

---

acir/src/native_types/expression/operators.rs

There was a typo in the implementation of the `Mul` operator for `Expressions`. 
https://github.com/noir-lang/acvm/blob/45c45f7cdb79c3ccb0373ca0e698b282d4dabc39/acir/src/native_types/expression/operators.rs#L196-L205
Both of these while-loops use `i1` to index into `linear_combinations` while the second should use `i2`. This results in either improper multiplication or panics when trying to read past the end of `rhs.linear_combinations`.
I've written a quick smoke test for the `Mul` operator along with another for `Add` (which was already covered by the smoketest for `add_mul`. The first commit shows this …

fix(acir): Fix `Expression` multiplication to correctly handle degree 1 terms

---

acvm/src/lib.rs

This adds a generic `OpcodeSolveFailed` error to the `OpcodeNotSolvable` error enum so backends can report other problems with solving an opcode. I encountered this problem when converting aztec_backend to the fallible traits.
I think the data carried still needs to be bikeshed, since only an error string is probably not enough information.

feat(acvm): Add generic error for failing to solve an opcode

---

acvm/src/lib.rs
acvm/src/pwg.rs
acvm/src/pwg/arithmetic.rs
acvm/src/pwg/blackbox.rs
acvm/src/pwg/block.rs
acvm/src/pwg/directives.rs
acvm/src/pwg/hash.rs
acvm/src/pwg/logic.rs
acvm/src/pwg/oracle.rs
acvm/src/pwg/range.rs
acvm/src/pwg/signature/ecdsa.rs

Works towards a resolution of the conversation at https://github.com/noir-lang/acvm/pull/247/files#r1180617953 and puts ACVM in a better position for self-implementing all of the opcodes (one by one).
This removes the `solve` function on the PartialWitnessGenerator trait and moves it into the `pwg` module as a standalone function that takes a backend. It also replaces `solve_black_box_function_call` with individual functions for each black box function being solved. This will allow us to systematically implement the blackbox function calls in ACVM and then remove them from the PWG interface for backends. Until (eventually) they are all gone and the backend doesn't need to implement anything for PWG; instead, just conforming to the ACVM implementation.
I've split these out into separate …

feat!: Remove `solve` from PWG trait & introduce separate solvers for each blackbox

---

acir_field/src/generic_ark.rs

Small issue I noticed while working on something else. I imagine the compiler optimises this away anyway but we can remove this call to `to_vec()` as `bytes` is already a `Vec<u8>`.

chore(acir_field): remove unnecessary `to_vec()`

---

acvm/src/compiler/transformers/fallback.rs
acvm/src/lib.rs
acvm/src/pwg/blackbox.rs
acvm/src/pwg/hash.rs
acvm/src/pwg/logic.rs
acvm/src/pwg/range.rs
acvm/src/pwg/signature/ecdsa.rs

Addresses issue raised in https://github.com/noir-lang/aztec_backend/pull/165
This PR updates all the black box solver functions to accept slices of inputs and outputs rather than wanting a `BlackBoxFuncCall`. This prevents us from having to construct them up in aztec_backend just to feed back into ACVM.
As part of this I've updated the `PartialWitnessGenerator` trait to stop passing an `outputs` argument to the range opcode solver as it has no outputs. We could go further and apply similar changes for opcodes with a specified number of inputs/outputs but that felt overkill.

feat(acvm)!: update black box solver interfaces to match `pwg:black_box::solve`

---

acvm/src/lib.rs
acvm/src/pwg/blackbox.rs

This name is inconsistent with the name of the matching solver function.
https://github.com/noir-lang/acvm/blob/0098b7d9640076d970e6c15d5fd6f368eb1513ff/acvm/src/pwg/hash.rs#L65
For consistency I've renamed it.

chore(acvm)!: rename `hash_to_field128_security` to `hash_to_field_128_security`

---

acvm/src/lib.rs

Resolves #272 (link to issue)
In order to use a Backend trait as a generic in a `thiserror` derived enum, we need the backend to implement Debug. See the linked issue and https://github.com/noir-lang/noir/pull/1322 for further context.

chore(acvm)!: Backend trait must implement Debug

---

acir/src/native_types/mod.rs
acir/src/native_types/witness_map.rs
cspell.json

When trying to update https://github.com/noir-lang/noir/pull/1267, we tried to map the WitnessMapError to a nargo error, but the type isn't exported so it can't be used to derive. This makes it public to consumers, but also hides the enum values so they can't be pattern matched and cause breaking changes if/when updated.

fix(acir): Hide variants of WitnessMapError and export it from package

---

acvm/Cargo.toml
acvm/src/lib.rs

Needed for https://github.com/noir-lang/acvm-backend-barretenberg/issues/160
This requires a `CommonReferenceString` trait for ACVM Backends.
The reason some functions in other traits were modified to take the `common_reference_string` is because backends can have a circular dependency, such that they need to instantiate themselves before they can get the circuit size for a given circuit and the CRS often needs the circuit size to the data it is using. This means we can't do `Backend::new(CRS::new(circuit_size))` and resulted the functions that need a CRS taking it as an argument.

feat(acvm)!: Add CommonReferenceString backend trait

---

acvm/Cargo.toml
acvm/src/lib.rs

Followup to https://github.com/noir-lang/acvm/pull/214
These functions were deprecated in the 0.10.0 release and so can be removed in 0.12.0.

chore!: Remove deprecated circuit hash functions

---

acir/src/circuit/opcodes/black_box_function_call.rs
acvm/src/lib.rs
acvm/src/pwg/blackbox.rs
acvm/src/pwg/signature/ecdsa.rs

Motivated by slack messages
This updates all variable/argument names related to ECDSA function to specify that it refers to the hash of the message rather than the message itself.

chore: replace all usages of `message` for ECDSA with `hashed_message`

---

acvm/src/lib.rs

Continuation of #264 -- Since the bakends are no longer solving particular opcodes, we can remove them from the PWG trait

chore!: Remove backend solvable opcodes from PWG trait

---

acir/src/circuit/black_box_functions.rs
acir/src/circuit/opcodes/black_box_function_call.rs
acvm/src/lib.rs
acvm/src/pwg.rs
acvm/src/pwg/blackbox.rs

Resolves #295 
This PR removes the `ComputeMerkleRoot` opcode.

feat!: remove `ComputeMerkleRoot` opcode

---

acvm/src/lib.rs

This allows implementors of `#[async_trait]` to not mark their functions as Send. This is needed because the browser fetch API is `async` but not `Send`.

fix!: Allow async functions without send on async trait

---

acvm/src/pwg.rs
acvm/src/pwg/brillig.rs
brillig_bytecode/src/lib.rs
brillig_bytecode/src/registers.rs
brillig_bytecode/src/value.rs

Resolves https://github.com/noir-lang/acvm/pull/152#discussion_r1201547932
Resolves https://github.com/noir-lang/acvm/pull/152#discussion_r1201547233
This PR makes the internal fields of `Value` and `RegisterIndex` private and exposes relevant getters / implements `From` to maintain functionality.

chore: make `Value` and `RegisterIndex` fields private

---

acir/src/circuit/opcodes/black_box_function_call.rs
acvm/src/pwg/blackbox.rs
acvm/src/pwg/hash.rs

feat!: Add variable length keccak opcode

---

acvm/src/pwg/brillig.rs

Resolves #303
This moves to get_value rather than calling `ArithmeticSolver::evaluate` directly in BrilligSolver. 
This move also lets us simplify the logic for determining whether the PWG needs to stall. Previously we were comparing the size of the inputs declared in the Brillig call to the input registers that were actually resolved against the witness. We can now get rid of this check as return with `OpcodeResolution::Stalled` directly inside the loop that is resolving the brillig inputs. Returning earlier also let us remove the `continue_eval` flag that told us to escape the brillig inputs resolution loop as to not add an unresolved array ID to the brillig input registers 

chore: Resolve TODO when handling inputs in the BrilligSolver to use get_value

---

acir/src/circuit/black_box_functions.rs
acir/src/circuit/mod.rs
acir_field/src/generic_ark.rs
acvm/src/compiler/optimizers/simplify.rs
acvm/src/pwg.rs
acvm/src/pwg/block.rs
acvm/src/pwg/brillig.rs
acvm/src/pwg/sorting.rs
brillig_vm/src/lib.rs
brillig_vm/src/opcodes.rs
brillig_vm/src/registers.rs

Resolves #306 #326
Various fixup changes. Includes a change to try and catch misuses of registers (by having an explicit uninitialized value)
Rename resolve_foreign_call_input for #306 
chore: Remove Field < and <= support from Brillig for #326 
N/A
Some minor test simplification as field LTE was no longer available

chore: Brillig BinaryFieldOp simplification, rename resolve_foreign_call_input

---

brillig_vm/src/opcodes.rs

Resolves #304
I decided that we don't really have issues. Before this function mentioned fields so it the check was vestigial, but while a signed int conversion might have an issue in general, in this case we're casting a division result which will never be larger than the operands

chore: resolve to_unsigned TODO

---

acvm/src/pwg.rs
acvm/src/pwg/brillig.rs
brillig_vm/src/lib.rs
cspell.json

Resolves #305 
Propagates error messages in failure() to the top of VM resolution
Future improvements would potentially also propagate the trace of 'call' functions (would need some debug-enabling func info data structure in the VM)
- [*] I have tested the changes locally.
- [*] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [*] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [*] I have reviewed the changes on GitHub, line by line.
- [*] I have ensured all changes are covered in the description.

fix(brillig): Proper error handling for Brillig failures

---

.github/workflows/release.yml
release-please-config.json

Resolves #301
This adds brillig to the release-please config so it can have a linked version and RP will create github releases for it.
I've also updated the release token so CI will run against the release PR.
While I was updating the release-please config, I removed the bootstrap sha that is no longer needed since we've already bootstrapped the project.

fix(ci): Add brillig_vm to release-please & link versions

---

acir/src/native_types/expression/mod.rs
acvm/src/compiler.rs
acvm/src/compiler/transformers/csat.rs

Reverts noir-lang/acvm#278
Putting this PR up as it seems to be breaking here: https://github.com/noir-lang/noir/pull/1509

chore: Revert "fix: re-use intermediate vars during width reduction"

---

brillig_vm/src/lib.rs

Brillig VM memory was fixed on initialization, which requires to always initialize it with an empty memory of the maximum size allowed.  
This PR expands the memory dynamically on store with zeroes. In the future we can add a feature of passing a maximum memory on VM creation to limit VM memory for applications where brillig is going to be verified with constrained resources, such as in a VM circuit.
Before:
```
```
After:
```
```

fix(brillig): expand memory with zeroes on store

---

acvm/src/pwg/blackbox/ecdsa.rs

Related to #300 
This PR sets out to enforce the proper lengths of inputs through the type system. This is useful for #300 as we'll be allowing user input here rather than this function only being called by the ACVM (which has stronger guarantees on passing correct length arrays.

chore: enforce `verify_prehashed` input lengths through types

---

acir/src/circuit/brillig.rs
acvm/src/pwg/mod.rs
brillig_vm/src/lib.rs

Resolves 
This PR aims to smooth out the devex of resolving a brillig foreign call by providing a helper function to generate an updated `Brillig` using the returned call result.
This allows us to use the snippet below
```rust
let result: ForeignCallResult = Oracle::do_brillig_foreign_call(unresolved_brillig_call.foreign_call_wait_info);
let new_brillig: Brillig = unresolved_brillig_call.resolve_foreign_call(result);
opcodes.push(Opcode::Brillig(new_brillig))
```
as opposed to having to extract the `Brillig` struct from the foreign call and manually push a new `ForeignCallResult` onto one of its fields.

feat: add method to generate the new `Brillig` opcode from `UnresolvedBrilligCall`

---

brillig_vm/src/opcodes.rs

Resolves #360
This PR sets out to
Before:
```
```
After:
```
```

fix(brillig): Explicitly wrap on arithmetic operations

---

acvm/src/pwg/mod.rs
brillig_vm/src/lib.rs

Cleanup ForeignCallResult to use an enum ForeignCallOutput rather than a nested vector. This makes the structure of each individual output clearer to developers and no longer mixes a single value w/ an array of size 1.
Resolves

chore(brillig_vm)!: Switch nested vector in ForeignCallResult to enum ForeignCallOutput

---

brillig_vm/src/lib.rs

Returning an incorrectly sized foreign call response to the Brillig VM will currently cause a panic. This is an issue for situations where the Brillig VM is running inside wasm as this doesn't handle panics well. As this is a case of a user providing invalid input, we should return an error rather than panicking.
Resolves https://github.com/noir-lang/acvm/pull/370#discussion_r1229659602
We now set the `VMStatus` to `Failure` in this situation. I've had to delay this until after the `for-loop` due to the borrow-checker so I'd be open to any other solutions which avoid the need for the mutable bool + break.

chore: set Brillig VM state to `Failure` rather than panicking on invalid foreign call response

---

acvm/src/pwg/blackbox/ecdsa.rs

Merge after #359 
This PR removes the unnecessary `ecdsa_secp256k1` submodule and deletes dead code.

chore: clean up ECDSA verification logic

---

Cargo.toml
acir/Cargo.toml
acir_field/Cargo.toml
acvm/Cargo.toml
brillig_vm/Cargo.toml
stdlib/Cargo.toml

Partial addresses warning at: https://github.com/noir-lang/acvm/actions/runs/5212404733/jobs/9405951422#step:5:11
We currently don't provide a repository link, homepage or documentation link. This PR adds a repo link so https://crates.io/crates/acvm links back here.
I've left off homepage/documentation as we don't have any ACVM resources currently.

chore: add repository link to `Cargo.toml` metadata

---

acvm/src/pwg/brillig.rs
acvm/src/pwg/mod.rs

Groundwork PR for #384 
We were including unnecessary mutability for the `Brillig` reference being passed to the `BrilligSolver`. If we make this immutable then we can treat brillig opcodes identically to non-oracle opcodes in the `OpcodeResolution::Stalled` condition.
I've also factored out a function to zero out all the outputs from a brillig opcode for readability-sake.

chore: Remove unnecessary mutability from `BrilligSolver`

---

brillig_vm/Cargo.toml
brillig_vm/src/lib.rs

`brillig_vm` didn't have the linting setup from other crates which resulted in an unnecessary dependency and an unreachable export.

chore: fix clippy issues in `brillig_vm`

---

acir/src/native_types/expression/operators.rs
acir/src/native_types/witness.rs

Resolves https://github.com/noir-lang/acvm/issues/321
Resolves https://github.com/noir-lang/acvm/issues/335
implement add trait for witness
make output of mul expression optional

feat!: add trait for witness & make output of mul expression optional

---

acvm/src/pwg/blackbox/ecdsa.rs
acvm/src/pwg/mod.rs

Resolves 
This PR removes an error variant which is unused

chore!: remove unused `OpcodeResolutionError::IncorrectNumFunctionArguments` variant

---

acvm/src/lib.rs

Resolves 
This adds `Copy` to the languages. There's no reason we should need to pass references for `Language` because it can derive copy.
This PR is applied to the 0.15.1 release so I can us it against noir but it should apply cleanly.

feat: Derive `Copy` for `Language`

---

acir/src/circuit/black_box_functions.rs
acir/src/circuit/opcodes/black_box_function_call.rs
acvm/src/lib.rs
acvm/src/pwg/blackbox/mod.rs
acvm/src/pwg/blackbox/signature/schnorr.rs
acvm/tests/solver.rs
cspell.json

This PR reverts the changes to the `SchnorrVerify` opcode made in https://github.com/noir-lang/acvm/pull/386. I've also defined this opcode more clearly.

fix(acir)!: revert changes to `SchnorrVerify` opcode

---

acvm/src/pwg/mod.rs
acvm/tests/solver.rs

Resolves 
This PR pulls the `ACVMStatus` enum from #399 so that it can be merged separately from the simplifications to the rest of the ACVM.
Also fixes an issue where the ACVM could not be finalised when fully solved.

feat(acvm)!: replace `PartialWitnessGeneratorStatus` with `ACVMStatus`

---

acvm/src/lib.rs

Adds `circuit: &Circuit` to the `eth_contract_from_vk` function signature in the `SmartContract` trait for ACVM backends
Halo2 Backend needs to know the number of public inputs to generate the smart contract verifier for proofs. With the ACVM backend API, there is currently no way to pass this value into `eth_contract_from_vk`.
Resolves: https://github.com/noir-lang/acvm/issues/411
Minimal changes- see description
Will require that `acvm-backend-barretenberg` passes in the ACIR even though it doesn't need it:
https://github.com/noir-lang/acvm-backend-barretenberg/blob/master/src/acvm_interop/smart_contract.rs#L12-L16
And that `nargo` supplies the ACIR when calling `eth_contract_from_vk` from the backend:
https://github.com/noir-lang/noir/blob/master/crates/nargo/src/ops/codegen_verifier.rs …

feat(acvm)!: Add `circuit: &Circuit` to `eth_contract_from_vk` function signature

---

brillig/src/opcodes.rs

I want to be able to use register indices however I may need in the code gen implementation of brillig. In this instance register indices are going to be used in a map to associate slices to their size at runtime.

feat: derive PartialOrd, Ord, and Hash on RegisterIndex

---

blackbox_solver/Cargo.toml
blackbox_solver/src/lib.rs
brillig_vm/Cargo.toml
brillig_vm/src/arithmetic.rs
brillig_vm/src/black_box.rs
brillig_vm/src/lib.rs
brillig_vm/src/registers.rs

Resolves 
The `acir` crate reexports the `acir_field` and `brillig` crates so I've simplified any consumers of these to use the versions from `acir`.

chore: remove unnecessary workspace dependencies

---

acvm/src/lib.rs

Resolves #300 
Resolves #372 
This PR adds a re-export for the `blackbox_solver` crate so that consumers of the ACVM can execute the blackbox opcodes externally.

feat(acvm): reexport `blackbox_solver` crate from `acvm`

---

acvm/Cargo.toml
acvm/src/pwg/directives/sorting.rs

Resolves 
This addresses some warnings about unused dev dependencies in the `acvm` crate.

chore: remove unused dev dependencies

---

acvm/src/pwg/directives/mod.rs

A directive should ideally not panic when we are dividing zero by zero. The input is not trusted and should be constrained, so it is okay to return 0 when we have 0/0.
Related: https://github.com/noir-lang/noir/issues/1802
Resolves

fix: Remove panic when we divide 0/0 in quotient directive

---

stdlib/src/blackbox_fallbacks/logic_fallbacks.rs
stdlib/src/blackbox_fallbacks/utils.rs

Resolves 
This PR adds special cases to the fallback implementations of logic black box functions. This removes unnecessary an unnecessary `toLeRadix` directive and the resulting dummy witness which just gets constrained to be equal to an existing witness.

feat: add optimisations to fallback black box functions on booleans

---

acir/src/circuit/opcodes/block.rs
acvm/src/pwg/arithmetic.rs
acvm/src/pwg/block.rs
acvm/src/pwg/mod.rs

Resolves 
This PR just does some code reorganisation and renaming of variables to make this function a little clearer.

chore: Improve readability of `BlockSolver.solve_memory_op`

---

Cargo.toml
acir/Cargo.toml
acir/src/circuit/brillig.rs
acir/src/circuit/mod.rs
acir/src/circuit/opcodes.rs
acvm/Cargo.toml
acvm/src/compiler/mod.rs
acvm/src/compiler/optimizers/redundant_range.rs
acvm/src/compiler/transformers/csat.rs
acvm/src/compiler/transformers/fallback.rs
acvm/src/pwg/block.rs
acvm/src/pwg/brillig.rs
acvm/src/pwg/mod.rs
acvm/tests/solver.rs

Janky implementation of stepwise execution.
This PR makes the assumption that each opcode can be executed on the first attempt (excluding foreign calls). We can then implement stepwise execution.

feat(acvm)!: Support stepwise execution of ACIR

---

acir/src/circuit/opcodes/black_box_function_call.rs

Resolves 
This function is no longer used by Noir (and was basically a hack) so I've deprecated it for later removal.

chore: deprecate `BlackBoxFuncCall::dummy()`

---

release-please-config.json

Resolves 
ACVM JS needs to be placed into the same group of linked versions as the ACVM package.

chore: keep ACVM JS in sync with ACVM version

---

acvm/src/pwg/mod.rs

The unsatisified constraint error message omitted the opcode label
Resolves

fix: add opcode label to unsatisfied constrain string

---

acir/src/circuit/mod.rs
acvm/src/compiler/mod.rs
acvm/src/compiler/optimizers/redundant_range.rs
acvm/src/compiler/transformers/fallback.rs
acvm/src/pwg/arithmetic.rs
acvm/src/pwg/blackbox/range.rs
acvm/src/pwg/brillig.rs
acvm/src/pwg/directives/mod.rs
acvm/src/pwg/memory_op.rs
acvm/src/pwg/mod.rs
acvm/tests/solver.rs

This PR allows to start locating errors inside brillig functions, by exporting a OpcodeLocation struct that can be used to locate both ACIR and Brillig opcodes. Also updated the ACIR optimizer to return a map of new location to old location to support keeping track of location of brillig opcodes.

feat!: Switched from OpcodeLabel to OpcodeLocation and ErrorLocation

---

acvm/src/pwg/mod.rs

Updates the string representation of opcode locations with fmt for easy parsing.

feat: print error location with fmt

---

acvm/src/lib.rs

Prerequisite for #492 
This PR separates the `BlackBoxFunctionSolver` trait from the `Backend` trait. This is a necessary step for #492 as these will become two distinct entities.

chore: split `BlackBoxFunctionSolver` off from `Backend` trait

---

Cargo.lock
acvm/Cargo.toml
acvm/src/lib.rs

Resolves 
This is no longer needed when using dynamic backends.

chore(acvm)!: remove `CommonReferenceString` trait and preprocess method

---

Cargo.lock
blackbox_solver/Cargo.toml
blackbox_solver/build.rs

Resolves 
This removes the necessity for consumers of ACVM to download the wasm themselves and set the environment variable.

chore: download the wasm binary in build.rs if no env var is provided

---

acvm/src/compiler/mod.rs

Towards https://github.com/noir-lang/noir/issues/2474

chore!: Return an iterator from `new_locations()` instead of collecting

---

acvm/src/lib.rs

Resolves 
This PR removes the ignored arguments from the `Backend` trait methods.

chore(acvm)!: Remove unused arguments from `Backend` trait

---

acir/src/circuit/mod.rs
acvm/src/compiler/mod.rs
acvm/src/compiler/optimizers/redundant_range.rs
acvm/tests/solver.rs
acvm_js/src/execute.rs

This temporarily removes the BTreeMap type for assert messages. For now, this will be more inefficient.
Resolves

chore: Remove BTreeMap type on assert_messages 

---

acvm/src/lib.rs

Resolves #280
Resolves #209
Resolves #256
Resolves #196
This PR removes the `Backend` trait as we will no longer need to communicate through this trait.

chore(acvm)!: Remove the `Backend` trait

---

acvm/src/pwg/brillig.rs
acvm/src/pwg/mod.rs
acvm/tests/solver.rs
acvm_js/src/execute.rs
acvm_js/src/foreign_call/mod.rs
acvm_js/src/js/executionError.js
acvm_js/src/js_execution_error.rs
acvm_js/src/lib.rs
brillig_vm/src/lib.rs

ACVM part of https://github.com/noir-lang/noir/issues/2550
- Brillig errors were never emitted from the ACVM, they were changed to an unsatisfied constraint error. Now they are emitted and they contain a call stack instead of a failing opcode, to be able to provide call stacks for brillig functions which are not inlined.
- Also, the acvm_js was throwing strings instead of errors. Now it throws JS errors and in the case of an execution failure, an error with a call stack property.
- Since the acvm_js now returns the failing opcode locations in a structured way, we can remove insertion of indices in OpcodeResolutionError

feat!: Provide runtime callstacks for brillig failures and return errors in acvm_js

---

acvm/src/pwg/blackbox/mod.rs

Recursive aggregation opcode is solved by the backend and cannot be solved by acvm. This can lead to missing assignment errors during execution.
Resolves 
To prevent these errors, we solve the opcode with zeros. The backend will resolved it properly after.

fix: initialize recursive proof output to zero

---

.github/workflows/test.yml

Resolves 
This uses the https://github.com/taiki-e/install-action action to install `wasm-bindgen-cli`. Under the hood this is using `cargo-binstall` which is listed as a [supported install method](https://github.com/rustwasm/wasm-bindgen#install-wasm-bindgen-cli)
This ends up shaving ~4mins off of CI

chore(ci): install `wasm-bindgen-cli` through prebuilt binary

---

flake.nix

chore: fix wasm build on macos

---

blackbox_solver/Cargo.toml

Cargo does not allow one to publish to crates.io with wildcards
Resolves

fix: use the exact version for the hex crate

---

acir/src/circuit/mod.rs

Resolves 
This PR encapsulates [this logic](https://github.com/noir-lang/noir/blob/f0032bbd8452164ed64c883b3a5a23c8a104726d/tooling/nargo/src/ops/execute.rs#L19-L25) into a method on `Circuit`.

feat(acir): add method on `Circuit` to return assert message

---

Cargo.toml
acvm/Cargo.toml
release-please-config.json

Resolves 
This PR ensures that release please will properly update the `acvm_blackbox_solver` dependency in `Cargo.toml`

chore: fix release-please config for `acvm_backend_solver`

---

release-please-config.json

chore: bump `brillig_vm` version in release please
