- Cargo.toml
- acir/Cargo.toml
- acir_field/Cargo.toml
- acvm/Cargo.toml
Addresses https://github.com/noir-lang/noir/issues/629 but for this repository
I've pulled up the shared dependencies into the workspace `Cargo.toml` file.
N/A
N/A
> chore: Move dependencies to a workspace `Cargo.toml` file

- acir/src/lib.rs
- acir/src/serialization.rs
- acir_field/src/lib.rs
- acvm/src/compiler/optimizers/general.rs
- acvm/src/lib.rs
- acvm/src/pwg/signature/ecdsa.rs
- acvm/src/pwg/sorting.rs
- stdlib/src/lib.rs
Equivalent of https://github.com/noir-lang/noir/pull/920 but for ACVM
> chore: restrict function visibility where overly broad

- acir/src/native_types/arithmetic.rs
I've copied across documentation from `noirc_evaluator` for the [equivalent functions defined over there](https://github.com/noir-lang/noir/blob/ed0e1ab4c7a3461da1a3fd500335d146ce43176c/crates/noirc_evaluator/src/ssa/acir_gen.rs#L172-L186)
> chore(acir): document various methods on `Expression`

- acvm/src/pwg/block.rs
Addresses some clippy warnings
> chore: clippy fixes

- acir/src/circuit/opcodes.rs
Make the id of BlockId public so we can create BlockId from a number.
We need to create the blocks in noir from the arrays
> chore(acir): public block id 

- acir/src/circuit/directives.rs
- brillig_bytecode/src/builder.rs
- brillig_bytecode/src/lib.rs
> feat: Add serialization for brillig bytecode

- acvm/Cargo.toml
- acvm/src/pwg/directives.rs
- brillig_bytecode/src/builder.rs
- brillig_bytecode/src/lib.rs
- brillig_bytecode/src/registers.rs
- brillig_bytecode/src/value.rs
> feat: Solve Brillig Directive

- brillig_bytecode/src/lib.rs
- brillig_bytecode/src/opcodes.rs
> feat: Add trap opcode

- acir/src/circuit/directives.rs
- brillig_bytecode/src/lib.rs
- brillig_bytecode/src/opcodes.rs
- brillig_bytecode/src/registers.rs
- brillig_bytecode/src/value.rs
> feat: Brillig JMP and JMPIF

- brillig_bytecode/src/lib.rs
> feat: JMPIFNOT

- acir/src/circuit/directives.rs
- acir/src/circuit/opcodes.rs
- acvm/src/compiler/transformers/fallback.rs
- acvm/src/lib.rs
- acvm/src/pwg.rs
- acvm/src/pwg/brillig.rs
- acvm/src/pwg/directives.rs
- brillig_bytecode/Cargo.toml
> chore(acir)!: Move Brillig from being a Directive to an ACIR Opcode

- acir/src/circuit/opcodes.rs
> fix: unwraps if inputs is zero

- brillig_bytecode/src/lib.rs
- brillig_bytecode/src/opcodes.rs
> feat: Brillig Call Opcode

- acir/src/circuit/opcodes.rs
- acvm/src/lib.rs
- acvm/src/pwg/brillig.rs
- brillig_bytecode/src/lib.rs
- brillig_bytecode/src/opcodes.rs
- brillig_bytecode/src/registers.rs
- brillig_bytecode/src/value.rs
This PR is the initial work to enable memory in unsafe functions using the ACVM. 
> feat: Brillig Memory

- acvm/src/lib.rs
> fix: Unresolved opcode fix for brillig

- acir/src/native_types/expression/mod.rs
- acir/src/native_types/expression/operators.rs
This PR migrates the remaining `Expression` arithmetic from [noirc_evaluator](https://github.com/noir-lang/noir/blob/809b85f751bd0e27ce8c4b38354bc051471d8522/crates/noirc_evaluator/src/ssa/acir_gen/constraints.rs#L55-L230). The aim behind this is so that we can remove some [very verbose usage of `add` and `subtract`](https://github.com/search?q=repo%3Anoir-lang%2Fnoir+subtract%28+add%28+language%3ARust&type=code&l=Rust) 
The `add` function has been changed to be the `add_mul` method on `Expression` so `a + k * b` can be called as `a.add_mul(k, b)`. I'm toying with the idea that this would be better named as …
> feat: implement `add_mul` on `Expression`

- brillig_bytecode/src/lib.rs
- brillig_bytecode/src/opcodes.rs
> feat!: Implement basic call stack for brillig VM

- acvm/src/pwg/hash.rs
Related to https://github.com/noir-lang/acvm/pull/259#discussion_r1184900185
> chore(acvm)!: Change blakes2s to blake2s256

- acvm/src/lib.rs
> chore: Add a PWG test that does two oracles in one Brillig opcode

- acir/src/circuit/black_box_functions.rs
- acir/src/circuit/opcodes/black_box_function_call.rs
- acvm/src/lib.rs
- acvm/src/pwg.rs
- acvm/src/pwg/blackbox.rs
> chore!: Remove AES opcode

- acvm/src/pwg.rs
- acvm/src/pwg/brillig.rs
- brillig_vm/src/lib.rs
> chore: Add documentation on how we handle unresolved foreign calls in Brillig

- acvm/src/lib.rs
> chore: Remove redundant comment

- acir/src/circuit/black_box_functions.rs
- acir/src/circuit/opcodes.rs
This PR copies across much of the documentations from https://github.com/noir-lang/docs/pull/163 into the code.
> chore: Document black box functions

- acvm/src/pwg/brillig.rs
> chore: Fixup comment to be more accurate in brillig solver

- acvm/src/compiler/transformers/fallback.rs
> fix(acvm): Do not panic when brillig opcode is encountered in fallback

- brillig_vm/src/lib.rs
Resolves 
If someone decides to make a foreign call that returns an array the Brillig compiler will be required to write extra opcodes (Const and Store) in order to allocate memory for the foreign call result if they do not want to overwrite previous memory locations. We currently expand when we reach memory limits on store and we should match this functionality for ForeignCall. 
I wrote a test showing this allocation for ForeignCall array outputs
Before:
```
```
After:
```
```
> chore(brillig_vm): Expand memory on ForeignCall outputs

- acvm/src/pwg/arithmetic.rs
- acvm/src/pwg/blackbox/ecdsa.rs
- acvm/src/pwg/directives/mod.rs
Resolves 
This PR ensures that we perform checks for any inconsistent writes to the witness map. These should trigger an unsatisfied constraint error.
> chore: perform checked writes to witness map

- .release-please-manifest.json
> chore: Add brillig and blackbox_solver to the release-please manifest

- release-please-config.json
Added missing entries in release-please for the root cargo.toml
> chore: fix release-please config for root

- .github/workflows/publish.yml
- README.md
> fix: Crate publishing order

- acir/Cargo.toml
> chore: Add `serialize-messagepack` feature flag 

- acvm/Cargo.toml
- acvm/src/compiler/transformers/fallback.rs
- acvm/tests/stdlib.rs
- stdlib/src/blackbox_fallbacks/blake2s.rs
- stdlib/src/blackbox_fallbacks/hash_to_field.rs
- stdlib/src/blackbox_fallbacks/mod.rs
- stdlib/src/blackbox_fallbacks/sha256.rs
- stdlib/src/blackbox_fallbacks/uint32.rs
> feat(stdlib): Add fallback implementation of `HashToField128Security` black box function

- .github/workflows/publish.yml
- .github/workflows/rust.yml
- .github/workflows/test.yml
- .github/workflows/typescript.yml
> chore(ci): update to actions/checkout@v4

- .github/workflows/deny.yml
- deny.toml
Resolves 
This PR actually starts denying wildcard dependencies
> chore(ci): deny wildcards
